# -*- coding: utf-8 -*-
"""rf-learning-tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/campusx-official/100-days-of-machine-learning/blob/main/day65-random-forest/rf_learning_tool.ipynb
"""

import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

X,y = make_classification(n_features=5, n_redundant=0, n_informative=5,n_clusters_per_class=1)

df = pd.DataFrame(X,columns=['col1','col2','col3','col4','col5'])
df['target'] = y
print(df.shape)
df.head()

# function for row sampling

def sample_rows(df,percent):
  return df.sample(int(percent*df.shape[0]),replace=True)

# function for feature sampling
import random
def sample_features(df,percent):
  cols = random.sample(df.columns.tolist()[:-1],int(percent*(df.shape[1]-1)))
  new_df = df[cols]
  new_df['target'] = df['target']
  return new_df

# function for combined sampling

def combined_sampling(df,row_percent,col_percent):
  new_df = sample_rows(df,row_percent)
  return sample_features(new_df,col_percent)

df1 = combined_sampling(df,0.5,0.5)
df1



df2 = combined_sampling(df,0.5,0.5)
df2

df3 = combined_sampling(df,0.5,0.5)
df3

print(df1.columns)
print(df2.columns)
print(df3.columns)

df3

from sklearn.tree import DecisionTreeClassifier
clf1 = DecisionTreeClassifier()
clf2 = DecisionTreeClassifier()
clf3 = DecisionTreeClassifier()

clf1.fit(df1.iloc[:,0:2],df1.iloc[:,-1])
clf2.fit(df2.iloc[:,0:2],df2.iloc[:,-1])
clf3.fit(df3.iloc[:,0:2],df3.iloc[:,-1])

from sklearn.tree import plot_tree

plot_tree(clf1)

plot_tree(clf2)

plot_tree(clf3)

clf1.predict(np.array([-0.764252,	1.341941	]).reshape(1,2))

clf2.predict(np.array([-0.764252,	1.341941	]).reshape(1,2))

clf3.predict(np.array([-0.764252,	1.341941	]).reshape(1,2))

df1

df.sample(14,replace=True)

