# -*- coding: utf-8 -*-
"""GBDT-Algo-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSeBSO22uMbCvlN10x0mxtBbx9Ap2nqM
"""

import pandas as pd
import numpy as np

df = pd.DataFrame([[165,137,472,192],[101,92,250,144],[29,127,201,91]],columns=['R&D','Ops','Marketing','Profit'])

df

df['f0(x)'] = df['Profit'].mean()
df

df['r1'] = df['Profit'] - df['f0(x)']
df

#

from sklearn.tree import DecisionTreeRegressor

reg = DecisionTreeRegressor(max_depth=3)

reg.fit(df.iloc[:,0:3].values, df.iloc[:,-1])

from sklearn.tree import plot_tree
plot_tree(reg)

# 165	137	472

